### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by NekoKetsu** [The-International-Screeps-Bot/Screeps-Grafana#5]
would it be possible to had a DockerFile for a easy-to deploy solution ?
if not i'm intersted in an example of a dockerFile for this repo

**Comment by pieterbrandsen** [comment]
@NekoKetsu I am going do this repo a little diferent as this personal one will become an base for the screeps as I would like to use the base for some other needed work.

You want the dockerfile to deploy this in somewhere?

**Comment by NekoKetsu** [comment]
wanted to try deploying on google cloud or something 
i'm just figuring out how to use docker's things outside of docker desktop

**Comment by pieterbrandsen** [comment]
@NekoKetsu  If you want we can move faster on discord: pieterthepanda

docker desktop is just an gui but I can explain more if you want

**Comment by pieterbrandsen** [comment]
No acitivty
